---
failure-threshold: info
label-schema:
  author: text
  contact: email
  version: semver
  license: spdx
no-color: false
no-fail: false
strict-labels: true
disable-ignore-pragma: false
trustedRegistries:
  - docker.io       # Official docker registry
  - "*.gcr.io"      # GCP container registry
  - "ghcr.io"       # GitHub container registry
ignored:
  - DL3049
