---
name: Set Up Python
description: Sets up Python, Package Manager, and installs CI dependencies
inputs:
  python-version:
    description: The Python version to set up
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065  # v5.6.0
      with:
        python-version: ${{ inputs.python-version }}

    - name: Read UV version from file
      id: read-uv-version
      run: |
        UV_VERSION=$(grep -E '^uv==[0-9.]+' requirements/uv.txt | cut -d '=' -f 3)
        echo "uv_version=$UV_VERSION" >> "$GITHUB_OUTPUT"
      shell: bash

    - name: Install package manager
      uses: astral-sh/setup-uv@c893ac1cb213677f58b781341aba739a586833bf  # v6.3.1
      with:
        version: "${{ steps.read-uv-version.outputs.uv_version }}"

    - name: Install CI dependencies
      run: python3 -m uv pip install --system --no-cache -r requirements/ci.txt
      shell: bash
