---
name: Set Up Python
description: Sets up Python, Package Manager, and installs CI dependencies
inputs:
  python-version:
    description: The Python version to set up
    required: true
  cache-suffix:
    description: Optional suffix appended to the uv cache key
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6.2.0
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install package manager
      uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b  # v8.1.0
      with:
        enable-cache: true
        cache-local-path: .cache/uv/build/tools
        cache-dependency-glob: |
          pyproject.toml
          tox.ini
          uv.lock
        cache-suffix: build-tools-${{ inputs.cache-suffix }}
        python-version: ${{ inputs.python-version }}
        version-file: "pyproject.toml"

    # TODO(eugengi): Skip installing uv package since setup-uv provisions uv binary.
    - name: Install CI dependencies
      env:
        UV_PROJECT_ENVIRONMENT: ${{ env.pythonLocation }}
      run: |
        uv sync --locked --no-default-groups --only-group ci
      shell: bash
