---
name: build
on:
  push:
    branches:
      - main
    paths:
      - src/**
      - tests/**
      - test_utils/**
      - .github/actions/**
      - .github/workflows/**
      - requirements/base.txt
      - requirements/ci.txt
      - requirements/prod.txt
      - requirements/test-ci.txt
      - requirements/uv.txt
  pull_request:
    branches:
      - "**"
    paths:
      - src/**
      - tests/**
      - test_utils/**
      - .github/actions/**
      - .github/workflows/**
      - requirements/base.txt
      - requirements/ci.txt
      - requirements/prod.txt
      - requirements/test-ci.txt
      - requirements/uv.txt

jobs:
  build:
    name: Build environments
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
        django-version:
          - django42
          - django50

    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 1  # Full history not required for build step.

      - name: Set up Python CI
        uses: ./.github/actions/setup-python-ci
        with:
          python-version: ${{ matrix.python-version }}

      - name: Restore tox environment cache
        uses: ./.github/actions/cache-tox-env
        with:
          python-version: ${{ matrix.python-version }}
          django-version: ${{ matrix.django-version }}

      - name: Prepare tox build environment
        run: |
          tox run -e ${{ matrix.django-version }} --notest
        shell: bash
